
(defun sh/launcher ()
  (interactive)
  (with-current-buffer (get-buffer-create "launcher")
    (let ((frame (make-frame '((name . "launcher")
                               (window-system . x)
                               (auto-raise . t)
                               (height . 10)
                               (internal-border-width . 20)
                               (left . 0.33)
                               (left-fringe . 0)
                               (line-spacing . 3)
                               (menu-bar-lines . 0)
                               (right-fringe . 0)
                               (tool-bar-lines . 0)
                               (top . 48)
                               (undecorated . nil)
                               (unsplittable . t)
                               (vertical-scroll-bars . nil)
                               (width . 10))))
          (alert-hide-all-notifications t)
          (inhibit-message t)
          (mode-line-format nil))
      )))

(provide 'sh-scripts)
